### ISSUE TITLE
No Scaling, no responsiveness

### ISSUE THREAD

**Issue by exinferis** [team-centric-software/simple-d3-heatmap#3]
To display a whole year a minimum fixed size of 1770 pixels is required, due to static boundaries, sizes and margins. This means it will not fit on any mobile Screen und is a close call on full hd as well.

**Comment by daluf** [comment]
simple scaling added: 1e2bf20a19f8603f4556c4e28fe36657a8d99c39
calendars now use full space if total screen width <800px: 8d74cd1118acac373fece223a96f67a6bd338f91
support for yearly calendar and increased label font size: 8fdec987800e8c77ff0be0ee89ba1379dfe1533c
also related:
26dd7bb94687a951f22dc934d8cad53ba77bd49b
cb68705015299a2fb397fc877b13eaa62accc2b6
3cbb0357198526bfa417aa1f41c0370cf04a3a6d
